/**
 * ASEC-073: Pull request creation from security fixes.
 *
 * Creates a pull request on the git platform that applies a
 * generated fix for a security finding.
 */

import type {Finding} from '../findings/types.js';
import type {GitPlatform} from '../providers/git-platform/types.js';
import type {FixSuggestion} from './auto-fix.js';

/** Options for PR creation. */
export interface CreateFixPROptions {
  /** Base branch to target (defaults to "main"). */
  baseBranch?: string;
  /** Head branch name (auto-generated if omitted). */
  headBranch?: string;
}

/**
 * Sanitizes a string for use in a branch name (lowercase alphanumeric + hyphens).
 */
function sanitizeBranchSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 40);
}

/**
 * Generates a branch name for a security fix PR.
 */
export function generateBranchName(finding: Finding): string {
  const slug = sanitizeBranchSegment(finding.title);
  const shortId = finding.id.substring(0, 8);
  return `asec/fix-${shortId}-${slug}`;
}

/**
 * Builds the PR title for a security fix.
 */
export function buildPRTitle(finding: Finding): string {
  const severityBadge = `[${finding.severity.toUpperCase()}]`;
  return `fix(security): ${severityBadge} ${finding.title}`;
}

/**
 * Builds the PR body for a security fix.
 */
export function buildPRBody(finding: Finding, fix: FixSuggestion): string {
  const parts: string[] = [
    '## Security Fix',
    '',
    `**Finding:** ${finding.title}`,
    `**Severity:** ${finding.severity}`,
    `**Confidence:** ${(fix.confidence * 100).toFixed(0)}%`,
  ];

  if (finding.cweId) {
    parts.push(`**CWE:** ${finding.cweId}`);
  }
  if (finding.file) {
    parts.push(`**File:** \`${finding.file}\``);
  }

  parts.push(
    '',
    '### Description',
    '',
    finding.description,
    '',
    '### Changes',
    '',
    fix.explanation,
    '',
    '### Original Code',
    '',
    '```',
    fix.original,
    '```',
    '',
    '### Fixed Code',
    '',
    '```',
    fix.fixed,
    '```',
    '',
    '---',
    `*Generated by AugmentaSec — Finding ID: \`${finding.id}\`*`,
  );

  return parts.join('\n');
}

/**
 * Creates a pull request on the given platform with a security fix.
 *
 * @param finding - The security finding being fixed.
 * @param fix - The generated fix suggestion.
 * @param platform - The git platform adapter.
 * @param options - Optional PR creation settings.
 * @returns The URL of the created pull request.
 */
export async function createFixPR(
  finding: Finding,
  fix: FixSuggestion,
  platform: GitPlatform,
  options: CreateFixPROptions = {},
): Promise<string> {
  const baseBranch = options.baseBranch ?? 'main';
  const headBranch = options.headBranch ?? generateBranchName(finding);
  const title = buildPRTitle(finding);
  const body = buildPRBody(finding, fix);

  return platform.createPullRequest(title, body, headBranch, baseBranch);
}
