export type {Severity, FindingSource, FindingStatus, Finding, FindingsReport, FindingsSummary} from './types.js';
export {createFinding, summarizeFindings} from './types.js';
export type {NormalizedFinding, NormalizedFindingsReport, SeverityCounts, ScanMetadata, RawFinding, ValidationError, ValidationResult} from './schema.js';
export {normalizeFinding, normalizeSeverity, normalizeConfidence, validateFinding, buildFindingsReport} from './schema.js';
export type {SeverityContext, SeverityScore} from './severity.js';
export {adjustSeverity, severityToNumber, numberToSeverity, isAtLeast, scoreSeverity} from './severity.js';
export type {DeduplicationStrategy, DuplicateGroup, DeduplicatedResult, DeduplicatedFinding} from './dedup.js';
export {deduplicateFindings, deduplicateWithCounts, levenshteinDistance, stringSimilarity} from './dedup.js';
export type {ComplianceFramework, ComplianceMapping, ComplianceReport, ComplianceSummary} from './compliance.js';
export {mapFindingToCompliance, generateComplianceReport, mapToOWASP, mapToCWE, mapToSANS25, complianceReport} from './compliance.js';
